export default {
  LOAD_TRANSACTIONS: 'LOAD_TRANSACTIONS',
  ERROR_LOAD_TRANSACTIONS: 'ERROR_LOAD_TRANSACTIONS',
  LOAD_CAUSES: 'LOAD_CAUSES',
  ERROR_LOAD_CAUSES: 'ERROR_LOAD_CAUSES',
  MAKE_DONATION: 'MAKE_DONATION',
  ERROR_MAKE_DONATION: 'ERROR_MAKE_DONATION'
};
